- frontend/src/components/ui/blockEditor/DirectoryViewer.jsx
- frontend/src/components/ui/blockEditor/Editor.jsx
- frontend/src/components/ui/blockEditor/TestLogs.jsx
- frontend/src/styles/block-editor.scss
- frontend/src/styles/globals.scss
- frontend/src/styles/library.scss
Remove duplicated tooltips, make tooltips overflow their container, add missing labels, rework the block editor scroll bars, make the tabs smaller when maximized
> CSS UI fixes

- frontend/agents/gpt-4_python_compute/generate/computations.py
- frontend/agents/gpt-4_python_view/generate/computations.py
- frontend/electron/main/index.ts
- setup.py
- Specify the python dependency versions
- this fixes an API issue with langchain for the chat agents
-  Add copy and paste menus to the whole app
> Specify the python dependencies versions

- frontend/src/App.jsx
- frontend/src/components/ui/MainContent.jsx
- frontend/src/styles/beautiful.css
> Make the Drawflow canvas use the full size of the content

- executor.go
- translator.go
Removing the last parameter type and copying `/files` everytime instead.
> Remove the file type from translation

- executor.go
- translator.go
> Revert "Remove the file type from translation"

- frontend/package.json
- frontend/server/express.mjs
- frontend/server/router.ts
- frontend/src/components/ui/LoadBlockButton.jsx
- frontend/src/components/ui/SaveAsPipelineButton.jsx
- frontend/src/components/ui/SavePipelineButton.jsx
- zetaforge/check_forge_dependencies.py
- zetaforge/forge_cli.py
- zetaforge/forge_runner.py
Removing bigint buffer, and using JS type instead, to surpress unnecessary error message
> Remove Bigint

- frontend/src/components/ui/blockGenerator/BlockGenerator.jsx
- Input values sent to graph properly wrapped with quotes
- Fixed issue where pasted values weren't wrapped with quotes
> Fix logic for quotes in textbox

- frontend/package.json
- frontend/src/main.jsx
- go.mod
- go.sum
- main.go
- Add sentry to the renderer process
- Add replays, 
- Add sentry to the go server
> Improve Sentry

- frontend/src/components/ui/DrawflowWrapper.jsx
- frontend/src/components/ui/RunPipelineButton.jsx
- frontend/src/utils/schemaValidation.js
- Evaluate only values property of pipeline (user input), all other properties are treated as optional for now
> Schema validation error

- README_PYPI.md
- pyproject.toml
- setup.py
This MR is targeted for creating a long description for pypi repository. In addition, it migrates some of the package metadata to pyproject.toml.
Notes to take:
- I created another README, README_PYPI.md, because I had to use external links to display the images.
View testpypi repo: https://test.pypi.org/project/zetaforge/
> Adding description for pypi repo

- frontend/server/router.ts
Fixes: `Failed to upload files to anvil server: TRPCClientError: uploadBlocks is not defined`
Reported here: https://discord.com/channels/1196886318035255296/1200205703357403187/1247569154848849981
> Hotfix uploadblocks not defined

- frontend/src/components/ui/LoadBlockButton.jsx
> Remove connections when loading a block

- frontend/src/components/ui/blockEditor/DirectoryViewer.jsx
> Put the click event on the TreeNode and not the span

- frontend/server/chat.js
- frontend/src/components/ui/blockEditor/ComputationsFileEditor.jsx
> Support old chat history version

- executor.go
- frontend/src/components/ui/Navbar.jsx
- frontend/src/components/ui/PipelineLogs.jsx
- frontend/src/components/ui/blockGenerator/BlockGenerator.jsx
- frontend/src/components/ui/useLoadPipeline.jsx
- main.go
- fixes empty log flash when the pipeline succeeds
> fix empty logs on success, fix termination when pipeline is not running

- executor.go
- frontend/src/components/ui/RunPipelineButton.jsx
- frontend/src/components/ui/SaveAsPipelineButton.jsx
- frontend/src/components/ui/useLoadPipeline.jsx
- main.go
fix history folder saving recursively
return schema validation error to client
> hotfix history folder

- frontend/package.json
- zetaforge/__init__.py
> version 0.2.0

- frontend/server/express.mjs
> Add back the missing endpoints for mixpanel

- frontend/.env
- frontend/config.js
- frontend/package.json
- frontend/server/anvil.js
- frontend/server/router.ts
- frontend/server/s3.js
- frontend/src/atoms/anvilConfigurationsAtom.js
- frontend/src/components/ui/Navbar.jsx
- frontend/src/components/ui/PipelineStopButton.jsx
- frontend/src/components/ui/RunPipelineButton.jsx
- frontend/src/components/ui/blockGenerator/BlockGenerator.jsx
- frontend/src/components/ui/modal/AnvilConfigurationForm.jsx
- frontend/src/components/ui/modal/AnvilConfigurationTable.jsx
- frontend/src/components/ui/modal/AnvilConfigurationsModal.jsx
- frontend/src/components/ui/useLoadPipeline.jsx
- frontend/src/migration/anvilConfigurationMigration.js
- frontend/src/utils/s3.js
> Add additional fields to the Anvil config screen

- frontend/server/anvil.js
- frontend/src/client/anvil.js
- frontend/src/components/ui/Navbar.jsx
- frontend/src/components/ui/PipelineStopButton.jsx
- frontend/src/components/ui/RunPipelineButton.jsx
- frontend/utils/HttpMethod.js
- frontend/utils/constants.js
- frontend/utils/urlBuilder.js
> Anvil HTTPS

- frontend/src/atoms/anvilConfigurationsAtom.js
- frontend/src/migration/anvilConfigurationMigration.js
> Add the configuration index to local storage

- frontend/src/components/ui/SaveAsPipelineButton.jsx
Add a missing mixpanel service variable
> Add missing mixpanel

- zetaforge/forge_runner.py
> chore: update forge_runner.py

- frontend/server/pipelineSerialization.js
Add a check in case both the pipeline specs blocks and the specs on disk have both parameters and containers
> Canny edge patch

- frontend/electron/preload/index.ts
- frontend/eslint.config.js
- frontend/server/router.ts
- frontend/src/atoms/pipelineAtom.js
- frontend/src/components/ui/NewButton.jsx
- frontend/src/components/ui/RunPipelineButton.jsx
- frontend/src/components/ui/WorkspaceFetcher.jsx
- frontend/src/hooks/useLoadPipeline.jsx
Closes #158 
It would be a good idea to manually QA this change set.
> Move the cache folder to the OS directory and remove the local .cache

- frontend/server/express.mjs
- frontend/src/components/ui/DrawflowWrapper.jsx
- frontend/src/components/ui/ExecutionDataGrid.jsx
- frontend/src/components/ui/SocketFetcher.jsx
- frontend/src/components/ui/WorkspaceFetcher.jsx
- frontend/src/components/ui/blockGenerator/BlockGenerator.jsx
- frontend/src/hooks/useExecutionResults.jsx
> Images through the express server

- translator.go
Implementing https://stackoverflow.com/questions/46085748/define-size-for-dev-shm-on-container-engine
> Add a dshm volume

- frontend/core/blocks/Image-to-Text/Dockerfile
- frontend/core/blocks/Image-to-Text/README.md
- frontend/core/blocks/Image-to-Text/computations.py
- frontend/core/blocks/Image-to-Text/requirements.txt
- frontend/core/blocks/Image-to-Text/specs.json
- frontend/core/blocks/google-drive-api/Dockerfile
- frontend/core/blocks/google-drive-api/README.md
- frontend/core/blocks/google-drive-api/computations.py
- frontend/core/blocks/google-drive-api/requirements.txt
- frontend/core/blocks/google-drive-api/specs.json
- Added changes for google drive api block
- Added changes to image to text block
> Added google drive api block and image to text block

- frontend/src/components/ZetaneDrawflowEditor.js
- frontend/src/styles/drawflow.scss
took like six hours due to missing `transform-origin: 0 0` amazing stuff css
> fix zoom to pointer

- frontend/src/components/ui/SaveAsPipelineButton.jsx
> fix regression

- frontend/server/s3.js
> Revert "Handle a 403 Error from S3 when users don't have full access to the S3 bucket"

- frontend/src/components/ui/blockEditor/directoryViewer/ActivePrompt.jsx
- frontend/src/components/ui/blockEditor/directoryViewer/Prompt.jsx
- frontend/src/components/ui/blockEditor/directoryViewer/PromptList.jsx
- frontend/src/components/ui/blockEditor/directoryViewer/PromptMenu.jsx
> Fix disabling the delete button

- executor.go
- main.go
- setup.go
- translator.go
Add k3d as a potential driver. Using the k3d cuda image let's a user run on gpu locally.
> Local gpu (k3d)

- frontend/package-lock.json
- frontend/package.json
- frontend/server/merkle.js
- frontend/server/pipelineSerialization.js
- frontend/src/components/ui/LoadPipelineButton.jsx
- frontend/src/components/ui/RunPipelineButton.jsx
- frontend/src/hooks/useLoadPipeline.jsx
- merkle tree no longer checks metadata from blocks
- track down local path to prevent losing history
> local local path correctly

- frontend/core/blocks/image-augmentations/requirements.txt
> fix image augmentation block

- frontend/core/pipelines/pipeline-text-to-app/README.md
> create README.md for core pipeline text to app
